apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2  # Number of desired replicas (pods)
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:alpine3.17  # Use the latest Nginx image from Docker Hub
          ports:
            - containerPort: 80  # Port the container listens on
